### ISSUE TITLE
Enhance composer examples script

### ISSUE THREAD

**Issue by peter279k** [tamtamchik/simple-flash#11]
Firstly, please look at following snippets on `composer.json` file:

```
......
 "scripts": {
    "tests": "vendor/bin/phpunit",
    "examples": "php -S localhost:8000 -t examples/"
  },
......
```

It will be failed when the `8000` port has been used.

To fix this error, I think it can consider using following approach:

- Create a `server.php` bash script file.
- Add option to let developers can specify port number.
- If the specific port number is not given, using the `8000` port by default.
- Check whether the port is used.
- If the port number is used, try to add number `1` to get new port number then try to setup sample server again.
- After trying three times, the port number is used, then stop retry port checking.
Print the message with `echo` and using exit code `1`.
- And the snippets on `composer.json` will be changed into:

```
......
 "scripts": {
    "tests": "vendor/bin/phpunit",
    "examples": "php sever.php"
  },
......

```

@tamtamchik, do you have any idea about this?

Once this issue has been accepted, I think I can work on this.

**Comment by tamtamchik** [comment]
Hi there,

Thank you for the suggestion, but I do not think that this is really important issue. 

This scripts entry is there just as a showcase of how to run the examples. So if the port `8000` is used by the third-party app user can always check the command and since it's very straightforward I do believe that it's not difficult to change the port manually by running the same command in the terminal with a different port:

`$ php -S localhost:8001 -t examples/`

Hiding this simple logic into separate file is an overkill, as for me.
